services:

  script:
    tty: true
    container_name: script
    image: my_script
    build:
      context: app/
      dockerfile: Dockerfile
    depends_on:
      - postgres-1
      - elasticsearch
    restart: on-failure
    networks:
      - etl_network

  postgres-1:
    container_name: postgres-2
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - etl_network
    restart: on-failure

  elasticsearch:
    container_name: elastic
    image: elasticsearch:7.5.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    networks:
      - etl_network
    restart: on-failure

networks:
  etl_network:
    name: etl_network
  