services:



  script:
    container_name: 'script'
    image: my_script
    build: .
    depends_on:
      - postgres
      - elasticsearch
    restart: on_failure
    networks:
      - etl_network

  postgres:
    container_name: 'postgres'
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - etl_network

  elasticsearch:
    container_name: elastic
    image: elasticsearch:7.5.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - etl_network

networks:
  etl_network:
    name: etl_network
  